name: guppy build

on:
  push:
    branches: [ "develop", "main" ]
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: mipsel-buildroot-linux-musl-

    runs-on: ubuntu-22.04
    container:
      image: pellcorp/guppydev:latest
      options: --user 1001
  
    env:
      CROSS_COMPILE: ${{ matrix.arch }}
      CC: ${{ matrix.arch }}
      CXX: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set guppyscreen nightly version
      run: |
        echo "GUPPYSCREEN_VERSION=${{ github.sha }}" >> $GITHUB_ENV

    - name: patch lv_drivers
      run: |
        git apply ../patches/0001-lv_driver_fb_ioctls.patch
      working-directory: ./lv_drivers

    - name: patch fmt in spdlog
      run: |
        git apply ../patches/0002-spdlog_fmt_initializer_list.patch
      working-directory: ./spdlog

    - name: patch dpi text scale in lvgl
      run: |
        git apply ../patches/0003-lvgl-dpi-text-scale.patch
      working-directory: ./lvgl

    - name: make wpaclient
      run: make wpaclient

    - name: make libhv
      run: make libhv.a
    
    - name: make libspdlog
      run: make libspdlog.a

    - name: make guppyscreen
      run: make -j

    - name: make kd_graphic_mode
      run: make kd_graphic_mode

    - name: package release
      run: |
        chmod +x ./release.sh
        ./release.sh

    - uses: actions/upload-artifact@v4
      with:
        name: guppyscreen
        path: ./guppyscreen.tar.gz

    - name: nightly release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: nightly
        tag_name: nightly
        files: guppyscreen.tar.gz
        fail_on_unmatched_files: true
